import HEAD from 'next/head'
import { ReactNode } from 'react'

interface HeadProps{
    children: ReactNode
}

const Head = ({ children }: HeadProps) => {
    return (
        <HEAD>
            <title>Sun Light</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            {/* <link rel="icon" href="/favicon.ico" /> */}
            <link rel="icon" href="/sun-fill.svg" />
            {children}
        </HEAD>
    )
}

export default Head